name: Run SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Run Bearer SAST
      run: |
        docker build -t sast-toolkit .
        docker run --rm -v ${{ github.workspace }}/src:/app/src sast-toolkit
