rules:
  - enabled: true
    severity: high
    tags: [sensitive-data, security]
scan:
  directory: /app/src
  filetypes: [".js", ".py", ".java", ".ts"]
output:
  format: json
  file: /app/results/output.json
